/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionBibliothèque;

import java.awt.Color;
import java.awt.FlowLayout;
import javax.swing.ComboBoxEditor;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Diallo
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        setLocationRelativeTo(null);
        desk.setLayout(new FlowLayout());
        jPanel1.setBackground(Color.white);
        //pane_search.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane_haut = new javax.swing.JPanel();
        lab_header = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        desk = new javax.swing.JDesktopPane();
        lab_image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        home_btn = new javax.swing.JButton();
        livres_btn = new javax.swing.JButton();
        utlisateur_btn = new javax.swing.JButton();
        Emprunts_btn = new javax.swing.JButton();
        reservation_btn = new javax.swing.JButton();
        deconnexion_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane_haut.setBackground(new java.awt.Color(153, 0, 51));

        lab_header.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        lab_header.setForeground(new java.awt.Color(255, 255, 255));
        lab_header.setText("Gestion de la bibliothèque");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Books_96px_1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Books_96px_1.png"))); // NOI18N

        javax.swing.GroupLayout pane_hautLayout = new javax.swing.GroupLayout(pane_haut);
        pane_haut.setLayout(pane_hautLayout);
        pane_hautLayout.setHorizontalGroup(
            pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_hautLayout.createSequentialGroup()
                .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_hautLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel18))
                    .addGroup(pane_hautLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)))
                .addGap(27, 27, 27)
                .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(pane_hautLayout.createSequentialGroup()
                        .addComponent(lab_header)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_hautLayout.createSequentialGroup()
                    .addGap(441, 441, 441)
                    .addComponent(jLabel19)
                    .addContainerGap(710, Short.MAX_VALUE)))
        );
        pane_hautLayout.setVerticalGroup(
            pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_hautLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_header, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pane_hautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_hautLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        desk.setBackground(new java.awt.Color(255, 255, 255));
        desk.setToolTipText("");

        lab_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/biblio1.jpg"))); // NOI18N

        desk.setLayer(lab_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskLayout.createSequentialGroup()
                .addComponent(lab_image, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        home_btn.setBackground(new java.awt.Color(225, 225, 225));
        home_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        home_btn.setText("Home");
        home_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 0, 153)));
        home_btn.setContentAreaFilled(false);
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.setOpaque(true);
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_btnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                home_btnMouseReleased(evt);
            }
        });
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        livres_btn.setBackground(new java.awt.Color(225, 225, 225));
        livres_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        livres_btn.setText("Livres");
        livres_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(153, 0, 0)));
        livres_btn.setContentAreaFilled(false);
        livres_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        livres_btn.setOpaque(true);
        livres_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                livres_btnMouseReleased(evt);
            }
        });
        livres_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livres_btnActionPerformed(evt);
            }
        });

        utlisateur_btn.setBackground(new java.awt.Color(225, 225, 225));
        utlisateur_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        utlisateur_btn.setText("Utilisateurs");
        utlisateur_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 102, 102)));
        utlisateur_btn.setContentAreaFilled(false);
        utlisateur_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        utlisateur_btn.setOpaque(true);
        utlisateur_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                utlisateur_btnMouseReleased(evt);
            }
        });
        utlisateur_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utlisateur_btnActionPerformed(evt);
            }
        });

        Emprunts_btn.setBackground(new java.awt.Color(225, 225, 225));
        Emprunts_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Emprunts_btn.setText("Emprunts");
        Emprunts_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(0, 102, 0)));
        Emprunts_btn.setContentAreaFilled(false);
        Emprunts_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Emprunts_btn.setMinimumSize(new java.awt.Dimension(69, 23));
        Emprunts_btn.setOpaque(true);
        Emprunts_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Emprunts_btnMouseReleased(evt);
            }
        });
        Emprunts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emprunts_btnActionPerformed(evt);
            }
        });

        reservation_btn.setBackground(new java.awt.Color(225, 225, 225));
        reservation_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reservation_btn.setText("Reservations");
        reservation_btn.setToolTipText("");
        reservation_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(204, 102, 0)));
        reservation_btn.setContentAreaFilled(false);
        reservation_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservation_btn.setOpaque(true);
        reservation_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reservation_btnMouseReleased(evt);
            }
        });
        reservation_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservation_btnActionPerformed(evt);
            }
        });

        deconnexion_btn.setBackground(new java.awt.Color(225, 225, 225));
        deconnexion_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deconnexion_btn.setText("Deconnexion");
        deconnexion_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 1, new java.awt.Color(51, 153, 0)));
        deconnexion_btn.setContentAreaFilled(false);
        deconnexion_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deconnexion_btn.setOpaque(true);
        deconnexion_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deconnexion_btnMouseReleased(evt);
            }
        });
        deconnexion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexion_btnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(livres_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utlisateur_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservation_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Emprunts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconnexion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(livres_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(utlisateur_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Emprunts_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservation_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(deconnexion_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pane_haut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desk))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane_haut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desk)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Emprunts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emprunts_btnActionPerformed
       this.desk.removeAll();
        this.desk.repaint();

        Emprunts ex = new Emprunts();
        desk.add(ex);
         lab_header.setText("Gestion des des Emprunts");
    }//GEN-LAST:event_Emprunts_btnActionPerformed

    private void Emprunts_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emprunts_btnMouseReleased
        home_btn.setBackground(new java.awt.Color(225,225,225));
        Emprunts_btn.setBackground(new java.awt.Color(0,204,04));
        livres_btn.setBackground(new java.awt.Color(225,225,225));
       // examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(225,225,225));
        // payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(225,225,225));
        deconnexion_btn.setBackground(new java.awt.Color(225,225,225));
        // tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_Emprunts_btnMouseReleased

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
         this.desk.removeAll();
         lab_image = new JLabel(new ImageIcon("images/biblio.PNG"));
         desk.add(lab_image);
        this.desk.repaint();
        
    }//GEN-LAST:event_home_btnActionPerformed

    private void home_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseReleased
        home_btn.setBackground(new java.awt.Color(51,153,255));
        Emprunts_btn.setBackground(new java.awt.Color(225,225,225));
        livres_btn.setBackground(new java.awt.Color(225,225,225));
       // examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(225,225,225));
        // payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(225,225,225));
        deconnexion_btn.setBackground(new java.awt.Color(225,225,225));
        // tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_home_btnMouseReleased

    private void home_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseExited
        //        candidatbtn.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_home_btnMouseExited

    private void home_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseEntered
        //     candidatbtn.setBackground(new java.awt.Color(51,2,255));
    }//GEN-LAST:event_home_btnMouseEntered

    private void reservation_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservation_btnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

       Reservations ex = new Reservations();
        desk.add(ex);
         lab_header.setText("Gestion des des Emprunts");
    }//GEN-LAST:event_reservation_btnActionPerformed

    private void reservation_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservation_btnMouseReleased
        livres_btn.setBackground(new java.awt.Color(225,225,225));
        home_btn.setBackground(new java.awt.Color(225,225,225));
        Emprunts_btn.setBackground(new java.awt.Color(225,225,225));
        //examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(225,225,225));
        //payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(255,153,0));
        deconnexion_btn.setBackground(new java.awt.Color(225,225,225));
        //tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_reservation_btnMouseReleased

    private void deconnexion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexion_btnActionPerformed
        /* this.desk.removeAll();
        this.desk.repaint();

        Depenses ex = new Depenses();
        this.desk.add(ex);
        try {
            ex.setMaximum(true);
        } catch (PropertyVetoException ex1) {
            Logger.getLogger(AcceuilGui.class.getName()).log(Level.SEVERE, null, ex1);
        }
        ex.show();*/
    }//GEN-LAST:event_deconnexion_btnActionPerformed

    private void deconnexion_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexion_btnMouseReleased
        livres_btn.setBackground(new java.awt.Color(225,225,225));
        home_btn.setBackground(new java.awt.Color(225,225,225));
        Emprunts_btn.setBackground(new java.awt.Color(225,225,225));
        //examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(225,225,225));
        //payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(225,225,225));
        deconnexion_btn.setBackground(new java.awt.Color(51,204,0));
        //tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_deconnexion_btnMouseReleased

    private void utlisateur_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utlisateur_btnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Utilisateurs ex = new Utilisateurs();
        desk.add(ex);
         lab_header.setText("Gestion des des Adhérents");
        
         
        
    }//GEN-LAST:event_utlisateur_btnActionPerformed

    private void utlisateur_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utlisateur_btnMouseReleased
        livres_btn.setBackground(new java.awt.Color(225,225,225));
        home_btn.setBackground(new java.awt.Color(225,225,225));
        Emprunts_btn.setBackground(new java.awt.Color(225,225,225));
        //examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(0,153,153));
        //payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(225,225,225));
        deconnexion_btn.setBackground(new java.awt.Color(225,225,225));
        //tarifbtn.setBackground(new java.awt.Color(225,225,225));
    }//GEN-LAST:event_utlisateur_btnMouseReleased

    private void livres_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livres_btnActionPerformed
        this.desk.removeAll();
        this.desk.repaint();

        Livres ex = new Livres();
        this.desk.add(ex);
       
        lab_header.setText("Gestion des livres");
       
        
        
  
    }//GEN-LAST:event_livres_btnActionPerformed

    private void livres_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livres_btnMouseReleased
        livres_btn.setBackground(new java.awt.Color(255,51,51));
        home_btn.setBackground(new java.awt.Color(225,225,225));
        Emprunts_btn.setBackground(new java.awt.Color(225,225,225));
        //examenbtn.setBackground(new java.awt.Color(225,225,225));
        utlisateur_btn.setBackground(new java.awt.Color(225,225,225));
        //payementbtn.setBackground(new java.awt.Color(225,225,225));
        reservation_btn.setBackground(new java.awt.Color(225,225,225));
        deconnexion_btn.setBackground(new java.awt.Color(225,225,225));
        //tarifbtn.setBackground(new java.awt.Color(225,225,225));
        
    }//GEN-LAST:event_livres_btnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Emprunts_btn;
    private javax.swing.JButton deconnexion_btn;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lab_header;
    private javax.swing.JLabel lab_image;
    private javax.swing.JButton livres_btn;
    private javax.swing.JPanel pane_haut;
    private javax.swing.JButton reservation_btn;
    private javax.swing.JButton utlisateur_btn;
    // End of variables declaration//GEN-END:variables
}
