/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionBibliothèque;

import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import Query.*;
import java.awt.HeadlessException;

/**
 *
 * @author Diallo
 */
public class Emprunts extends javax.swing.JPanel {

    /**
     * Creates new form Livres
     */
    public Emprunts() {
        initComponents();
        
        if (ConnectionDB.connexionBD() != null){
            table();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_actualiser = new javax.swing.JButton();
        bnt_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListeLivres = new javax.swing.JTable();
        btn_modifier1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textIDL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textTitre = new javax.swing.JTextField();
        textAuteur = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textIsbn = new javax.swing.JTextField();
        textType = new javax.swing.JTextField();
        textEtat = new javax.swing.JTextField();
        textStock = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboRecherche = new javax.swing.JComboBox<>();
        textSearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_actualiser.setBackground(new java.awt.Color(153, 0, 51));
        btn_actualiser.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_actualiser.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualiser.setText("Actualiser");
        btn_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiserActionPerformed(evt);
            }
        });

        bnt_supprimer.setBackground(new java.awt.Color(153, 0, 51));
        bnt_supprimer.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        bnt_supprimer.setForeground(new java.awt.Color(255, 255, 255));
        bnt_supprimer.setText("Supprimer");
        bnt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setBackground(new java.awt.Color(153, 0, 51));
        btn_modifier.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tableListeLivres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idem", "Date emp", "Date de retour", "Jours de retard", "Livre retouné", "Droits", "Id emprunteur"
            }
        ));
        tableListeLivres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListeLivresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListeLivres);

        btn_modifier1.setBackground(new java.awt.Color(153, 0, 51));
        btn_modifier1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_modifier1.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier1.setText("Ajouter");
        btn_modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Emprunt");

        textIDL.setEditable(false);
        textIDL.setBackground(new java.awt.Color(153, 0, 51));
        textIDL.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textIDL.setForeground(new java.awt.Color(255, 255, 255));
        textIDL.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel10.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Id emprunt");

        jLabel11.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Id emprunteur");

        textTitre.setBackground(new java.awt.Color(153, 0, 51));
        textTitre.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textTitre.setForeground(new java.awt.Color(255, 255, 255));
        textTitre.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textAuteur.setBackground(new java.awt.Color(153, 0, 51));
        textAuteur.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textAuteur.setForeground(new java.awt.Color(255, 255, 255));
        textAuteur.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel9.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Date emprunt");

        jLabel12.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Date de retour");

        textIsbn.setBackground(new java.awt.Color(153, 0, 51));
        textIsbn.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textIsbn.setForeground(new java.awt.Color(255, 255, 255));
        textIsbn.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textType.setBackground(new java.awt.Color(153, 0, 51));
        textType.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textType.setForeground(new java.awt.Color(255, 255, 255));
        textType.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textEtat.setBackground(new java.awt.Color(153, 0, 51));
        textEtat.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textEtat.setForeground(new java.awt.Color(255, 255, 255));
        textEtat.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        textStock.setBackground(new java.awt.Color(153, 0, 51));
        textStock.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        textStock.setForeground(new java.awt.Color(255, 255, 255));
        textStock.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Taxes");

        jLabel17.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Jours de retard");

        jLabel13.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Livre retourné");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textEtat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(textType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textIsbn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textAuteur, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textTitre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textIDL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textStock))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIDL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTitre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAuteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIsbn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEtat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel4.setText("Rechercher par :");

        comboRecherche.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        comboRecherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titre", "Auteur", "Type", "Etat", "Isbn", "Stock", "Disponibilité" }));
        comboRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRechercheActionPerformed(evt);
            }
        });

        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSearchKeyTyped(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 0, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_supprimer))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboRecherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualiser)
                            .addComponent(btn_modifier1))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnt_supprimer)
                            .addComponent(btn_modifier)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableListeLivresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListeLivresMouseClicked
        //remplirChamps();
        afficherSurLesChamps();
    }//GEN-LAST:event_tableListeLivresMouseClicked

    private void btn_actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiserActionPerformed
       table();
       viderChamps();
    }//GEN-LAST:event_btn_actualiserActionPerformed

    private void bnt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_supprimerActionPerformed
       int option= JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce livre ?", "Attention !", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION){
            supprimer();
            table();
        }
    }//GEN-LAST:event_bnt_supprimerActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
        int option= JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ce livre ?", "Attention !", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION){
            modifier();
            table();
            viderChamps();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void btn_modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier1ActionPerformed
      
    }//GEN-LAST:event_btn_modifier1ActionPerformed

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        search();
    }//GEN-LAST:event_textSearchKeyReleased

    private void textSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyTyped
        search();
    }//GEN-LAST:event_textSearchKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        search();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRechercheActionPerformed

    
    public void afficherSurLesChamps(){
        try
          {
            int ligne=tableListeLivres.getSelectedRow();
            String clic=(tableListeLivres.getModel().getValueAt(ligne,0).toString());
            ResultSet rs =  new BDD().querySelectAll("livre", "idl=' "+clic+" ' ");
            
            while(rs.next())
             {
               
              textIDL.setText(rs.getString(1));
             
              textAuteur.setText(rs.getString(3));
              textIsbn.setText(rs.getString(4));
              textType.setText(rs.getString(5));
              textEtat.setText(rs.getString(6));
             
                  }
                }
     catch(SQLException e)
      {          System.out.println(""+e.getMessage());
        }

    }
  
   public void modifier (){
       int idl = Integer.parseInt(textIDL.getText());
       
       String [] colonneDB = {"idl", "titre", "auteur", "sbn", "type", "etat", "stock", "description", "disponibilite" }  ; 
       String [] contenu  = { textIDL.getText(), textAuteur.getText(), textIsbn.getText(), textType.getText(),
                                       textEtat.getText()};
       
       String rsUpdate = new BDD().queryUpdate("livre", colonneDB, contenu, "idl=' "+idl+" ' ");
 
       System.out.println(""+rsUpdate);
       JOptionPane.showMessageDialog(null, "Livre modifié  !");
   }
   
   public void supprimer(){
        int idl = Integer.parseInt(textIDL.getText());
       String  rsDelete = new BDD().queryDelete("livre", "idl=' "+idl+" ' ");
       System.out.println(""+rsDelete);
       JOptionPane.showMessageDialog(null, "Ce livre a été bien supprimé"); 
       viderChamps();
   }
    
   public void table(){
       String a[]={"Idl","Titre","Auteur","Sbn","Type","Etat","Stock","description","Disponibilite" };
        ResultSet rs = new BDD().querySelect("livre",a);
        tableListeLivres.setModel(new ResultSetTableModel(rs));
            
   }
   
    @SuppressWarnings("null")
   
   
   public void viderChamps() {
       textIDL.setText("");
       textAuteur.setText("");
      
       textEtat.setText("");
      
       textIsbn.setText("");
       textType.setText(""); 
   }
   
   public void search(){
       ResultSet rs;
       PreparedStatement ps;
    try {
            String sql = "select idl as 'ID', titre as 'Titre' ,auteur as 'Auteur' ,sbn as 'Isbn' ,type as 'Type',etat As 'Etat',stock as 'Stock',description as 'Description',disponibilite as 'Disponibilité' from  livre where ";
           
           switch (comboRecherche.getSelectedItem().toString()) {
               case "Titre":
                   sql+="titre LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
//             byte[] imagedata =rs.getBytes("image");
//                Format = new ImageIcon(imagedata);
//                image.setIcon(Format);
           // ps.close();
           //rs.close();
               case "Auteur":
                   sql+="auteur LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               case "Type":
                   sql+="type LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               case "Etat":
                   sql+="etat LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               case "Isbn":
                   sql+="sbn LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               case "Disponibilité":
                   sql+="disponibilite LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               case "Stock":
                   sql+="stock LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableListeLivres.setModel(new ResultSetTableModel(rs));
                   break;
               default:
                   JOptionPane.showMessageDialog(null, "item selectionné et texte entré ne correspondent pas.");
                   break;
           }
        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        } finally {

            try {
                //ps.close();
                //rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
     
      
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_supprimer;
    private javax.swing.JButton btn_actualiser;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_modifier1;
    private javax.swing.JComboBox<String> comboRecherche;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListeLivres;
    private javax.swing.JTextField textAuteur;
    private javax.swing.JTextField textEtat;
    private javax.swing.JTextField textIDL;
    private javax.swing.JTextField textIsbn;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textStock;
    private javax.swing.JTextField textTitre;
    private javax.swing.JTextField textType;
    // End of variables declaration//GEN-END:variables

   
}
