/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionBibliothèque;

import Query.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Diallo
 */
public class Utilisateurs extends javax.swing.JPanel {

    /**
     * Creates new form Livres
     */
    public Utilisateurs() {
        initComponents();
      if (ConnectionDB.connexionBD() != null){
          table();
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        textDispo = new javax.swing.JComboBox<>();
        btn_actualiser = new javax.swing.JButton();
        bnt_supprimer = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEmprunteur = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        idEmprunt = new javax.swing.JTextField();
        labIdEmprunt = new javax.swing.JLabel();
        labDateEmprunt = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        labDateEmprunt1 = new javax.swing.JLabel();
        labdateRetour = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        labjRetard = new javax.swing.JLabel();
        labTaxe = new javax.swing.JLabel();
        codeEmprunt = new javax.swing.JTextField();
        dateIns = new javax.swing.JTextField();
        labTaxe1 = new javax.swing.JLabel();
        labTaxe2 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ufr = new javax.swing.JTextField();
        filiere = new javax.swing.JTextField();
        labTaxe4 = new javax.swing.JLabel();
        labTaxe3 = new javax.swing.JLabel();
        labTaxe5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_modifier1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textSearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboRecherche = new javax.swing.JComboBox<>();

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textDispo.setBackground(new java.awt.Color(153, 0, 51));
        textDispo.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        textDispo.setForeground(new java.awt.Color(255, 255, 255));
        textDispo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner", "true", "false" }));
        textDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDispoActionPerformed(evt);
            }
        });

        btn_actualiser.setBackground(new java.awt.Color(153, 0, 51));
        btn_actualiser.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_actualiser.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualiser.setText("Actualiser");
        btn_actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualiserActionPerformed(evt);
            }
        });

        bnt_supprimer.setBackground(new java.awt.Color(153, 0, 51));
        bnt_supprimer.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        bnt_supprimer.setForeground(new java.awt.Color(255, 255, 255));
        bnt_supprimer.setText("Supprimer");
        bnt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_supprimerActionPerformed(evt);
            }
        });

        btn_modifier.setBackground(new java.awt.Color(153, 0, 51));
        btn_modifier.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_modifier.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        tableEmprunteur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idl", "Nom", "Prénoms", "Téléphone", "Adresse", "Code emprunt", "Date ins", "CIN", "E-mail", "UFR", "Filière"
            }
        ));
        tableEmprunteur.setAutoscrolls(false);
        tableEmprunteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmprunteurMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableEmprunteur);

        idEmprunt.setEditable(false);
        idEmprunt.setBackground(new java.awt.Color(153, 0, 51));
        idEmprunt.setForeground(new java.awt.Color(255, 255, 255));
        idEmprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmpruntActionPerformed(evt);
            }
        });

        labIdEmprunt.setText("Id");

        labDateEmprunt.setText("Nom");

        nom.setBackground(new java.awt.Color(153, 0, 51));
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        prenom.setBackground(new java.awt.Color(153, 0, 51));
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });

        labDateEmprunt1.setText("Prénom");

        labdateRetour.setText("Téléphone");

        telephone.setBackground(new java.awt.Color(153, 0, 51));
        telephone.setForeground(new java.awt.Color(255, 255, 255));
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });

        adresse.setBackground(new java.awt.Color(153, 0, 51));
        adresse.setForeground(new java.awt.Color(255, 255, 255));
        adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseActionPerformed(evt);
            }
        });

        labjRetard.setText("Adresse");

        labTaxe.setText("Code emprunt");

        codeEmprunt.setBackground(new java.awt.Color(153, 0, 51));
        codeEmprunt.setForeground(new java.awt.Color(255, 255, 255));
        codeEmprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeEmpruntActionPerformed(evt);
            }
        });

        dateIns.setBackground(new java.awt.Color(153, 0, 51));
        dateIns.setForeground(new java.awt.Color(255, 255, 255));
        dateIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateInsActionPerformed(evt);
            }
        });

        labTaxe1.setText("Date incription");

        labTaxe2.setText("CIN");

        cin.setBackground(new java.awt.Color(153, 0, 51));
        cin.setForeground(new java.awt.Color(255, 255, 255));
        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        email.setBackground(new java.awt.Color(153, 0, 51));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        ufr.setBackground(new java.awt.Color(153, 0, 51));
        ufr.setForeground(new java.awt.Color(255, 255, 255));
        ufr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufrActionPerformed(evt);
            }
        });

        filiere.setBackground(new java.awt.Color(153, 0, 51));
        filiere.setForeground(new java.awt.Color(255, 255, 255));
        filiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filiereActionPerformed(evt);
            }
        });

        labTaxe4.setText("UFR");

        labTaxe3.setText("E-mail");

        labTaxe5.setText("Filière");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Adherant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labTaxe5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTaxe4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTaxe2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTaxe1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(labDateEmprunt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labIdEmprunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labDateEmprunt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labdateRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labjRetard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTaxe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labTaxe3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ufr)
                    .addComponent(idEmprunt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nom)
                    .addComponent(prenom)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adresse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(telephone, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dateIns)
                    .addComponent(email)
                    .addComponent(filiere)
                    .addComponent(cin))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIdEmprunt)
                    .addComponent(idEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDateEmprunt)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDateEmprunt1)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labdateRetour)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labjRetard)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeEmprunt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ufr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTaxe5))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btn_modifier1.setBackground(new java.awt.Color(153, 0, 51));
        btn_modifier1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        btn_modifier1.setForeground(new java.awt.Color(255, 255, 255));
        btn_modifier1.setText("Ajouter");
        btn_modifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier1ActionPerformed(evt);
            }
        });

        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSearchKeyTyped(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(153, 0, 51));
        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jLabel4.setText("Rechercher par :");

        comboRecherche.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        comboRecherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nom", "Prénom", "Code emprunt", "Date inscription", "E-mail", "CIN", "Adesse", "UFR", "Filière" }));
        comboRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboRecherche, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSearch))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_modifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modifier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnt_supprimer))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(textDispo, 0, 0, Short.MAX_VALUE)
                .addGap(861, 861, 861))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btn_modifier1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_modifier))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btn_actualiser)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bnt_supprimer)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1042, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
          int option= JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ce livre ?", "Attention !", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION){
            modifier();
            table();
            viderChamps();
        }
    }//GEN-LAST:event_btn_modifierActionPerformed

    private void bnt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_supprimerActionPerformed
          int option= JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce livre ?", "Attention !", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION){
            supprimer();
            table();
        }
    }//GEN-LAST:event_bnt_supprimerActionPerformed

    private void btn_actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualiserActionPerformed
         table();
        viderChamps();
    }//GEN-LAST:event_btn_actualiserActionPerformed

    private void textDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDispoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDispoActionPerformed

    private void idEmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmpruntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmpruntActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseActionPerformed

    private void codeEmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeEmpruntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeEmpruntActionPerformed

    private void dateInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateInsActionPerformed

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void ufrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufrActionPerformed

    private void filiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filiereActionPerformed

    private void btn_modifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifier1ActionPerformed

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        search();
    }//GEN-LAST:event_textSearchKeyReleased

    private void textSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyTyped
        search();
    }//GEN-LAST:event_textSearchKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         search();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRechercheActionPerformed

    private void tableEmprunteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmprunteurMouseClicked
        remplirChamps();
         
    }//GEN-LAST:event_tableEmprunteurMouseClicked

    
     public void table(){
       String a[]={"ide","Nom","Prenom","numtel","adresse","codeEmprunt","dateIns","numCni","email", "ufr", "filiere" };
        ResultSet rs = new BDD().querySelect("emprunteur",a);
       tableEmprunteur.setModel(new ResultSetTableModel(rs));
   }
     
     public void remplirChamps(){
         idEmprunt.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),0)));
        
        nom.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),1)));
        
        prenom.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),2)));
        
        telephone.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),3)));
        
        adresse.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),4)));
        
        codeEmprunt.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),5)));
        
        dateIns.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),6)));
        
        cin.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),7)));
        
        email.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),8)));
        
        ufr.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),9)));
        
        filiere.setText(String.valueOf(tableEmprunteur.getValueAt(tableEmprunteur.getSelectedRow(),10)));
    }   
    
     public void supprimer(){
        int ide = Integer.parseInt(idEmprunt.getText());
       String  rsDelete = new BDD().queryDelete("emprunteur", "ide=' "+ide+" ' ");
       System.out.println(""+rsDelete);
       JOptionPane.showMessageDialog(null, "Cet adhérent a été bien supprimé"); 
       viderChamps();
   } 
 
    public void viderChamps() {
       idEmprunt.setText("");
       nom.setText("");
       prenom.setText("");
       telephone.setText("");
       adresse.setText("");
       codeEmprunt.setText("");
       dateIns.setText("");
       cin.setText("");
       email.setText(""); 
       ufr.setText("");
       filiere.setText(""); 
   }
    
     public void modifier (){
       int ide = Integer.parseInt(idEmprunt.getText());
       
       String colonneEmprunteur[]={"ide","Nom","Prenom","numtel","adresse","codeEmprunt","dateIns","numCni","email", "ufr", "filiere" };
       String [] contenu  = { idEmprunt.getText(), nom.getText(), prenom.getText(), telephone.getText(), adresse.getText(),
                                       codeEmprunt.getText(), dateIns.getText(), cin.getText(), email.getText(), ufr.getText(), filiere.getText()};
       
       String rsUpdate = new BDD().queryUpdate("emprunteur", colonneEmprunteur, contenu, "ide=' "+ide+" ' ");
 
       System.out.println(""+rsUpdate);
       JOptionPane.showMessageDialog(null, "Emprunteur modifié  !");
   }
      
     public void search(){
      
         ResultSet rs;
       PreparedStatement ps;
    try {
            String sql = "select ide as 'ide', nom as 'Nom' ,prenom as 'Prénom' ,numtel as 'Téléphone', adresse as 'Adresse',codeEmprunt As 'Code emprunt',dateIns as 'Date inscription', numCni as 'CNI',email as 'E-mail' ,ufr as 'UFR' ,filiere as 'Filière' from  emprunteur where ";
           
           switch (comboRecherche.getSelectedItem().toString()) {
              
               case "Nom":
                   sql+="Nom LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
      
               case "Prénom":
                   sql+="Prenom LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "Téléphone":
                   sql+="numtel LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "Adesse":
                   sql+="adresse LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "Code emprunt":
                   sql+="codeEmprunt LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "Date inscription":
                   sql+="dateIns LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "E-mail":
                   sql+="email LIKE ?";
                   ps =  ConnectionDB.connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
                    case "UFR":
                   sql+="ufr LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               case "Filière":
                   sql+="filiere LIKE ?";
                   ps = new ConnectionDB().connexionBD().prepareStatement(sql);
                   ps.setString(1, "%"+textSearch.getText()+"%");
                   rs = ps.executeQuery();
                   tableEmprunteur.setModel(new ResultSetTableModel(rs));
                   break;
                   
               default:
                   JOptionPane.showMessageDialog(null, "L'item selectionné et le texte entré ne correspondent pas.");
                   break;
           }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {

            try {
                //ps.close();
                //rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
     
      
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton bnt_supprimer;
    private javax.swing.JButton btn_actualiser;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_modifier1;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField codeEmprunt;
    private javax.swing.JComboBox<String> comboRecherche;
    private javax.swing.JTextField dateIns;
    private javax.swing.JTextField email;
    private javax.swing.JTextField filiere;
    private javax.swing.JTextField idEmprunt;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labDateEmprunt;
    private javax.swing.JLabel labDateEmprunt1;
    private javax.swing.JLabel labIdEmprunt;
    private javax.swing.JLabel labTaxe;
    private javax.swing.JLabel labTaxe1;
    private javax.swing.JLabel labTaxe2;
    private javax.swing.JLabel labTaxe3;
    private javax.swing.JLabel labTaxe4;
    private javax.swing.JLabel labTaxe5;
    private javax.swing.JLabel labdateRetour;
    private javax.swing.JLabel labjRetard;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTable tableEmprunteur;
    private javax.swing.JTextField telephone;
    private javax.swing.JComboBox<String> textDispo;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField ufr;
    // End of variables declaration//GEN-END:variables

   
}
